language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: HUMch9qO/sk6mteOcFesIg+xzsqYyVZFeCirB/oxJdesNHv2HOFH6LrEms0+Vqd94rK/0eaA/bO2HENv92tRr5wVFKTfMtDE4/7vocckSiJKCMEr4qvRqhosTtTdD4K0IryXQd+XY9uDTZXAvXDRTX08dzaPvieQlOJUof1Or3Yy/e/a63Xdu1Mi9IuWSDqMJGaaJdUHHAYfvhK0aLN8Sh+FypbxKZDC91dsTqyUjXGQi3AylRE82kxB2PBtmYMTqhKI9IRdNXlPZzUtqYURKfsFjKp0K6Ripo2/kNkISk97CFFg7XUM4M2/8EsyV1droDg5UKPFIYb/xXkq71j22HclOdla7wW+Ed8tvsVvL5R6YPhpZ6yfUmOGhaRnucQWWLc0zSHgclFamJ9z6WvcgOAvSoUvn+gBZG1SKP4Cc7JYF0FSHbTd74sJx/0PbvQMqfb1RkYe4edtax8Rdr/gl7hv8KxqsNDekCP4IRQ5SGnk01ZGJ5x7zIz7TVIM3fA6OP7I1cWvqPCZ+sG4UFERHTGaZ8krC0ndyECAZMFuZmSpUduShk2q5xg/w+/74dgg4J+NMiqwX10RKasgIYNE4ZR8w5Q9S/8v03Lo7XljDFbEuXH5OMTeCWk0jHSoW0NiFpS3EYq/z1JpZqAinoMlJ+4usZfwOyRmON3DymIBNOk=
    - secure: dRsXBR2hbnwObLXf6CyiJLbL+y891sttqn/Bik6SNBqImTzVm/mLjRF8shzjZo45xFNJNteWqLBWfqEie6HNbez5Mvb8EqZPPbZrK4MoELvLHP33h5bE9Tkb2m+3K/dGY4wmD7ALf18NMPXctPKCSmdVXPYYLFFXBSHX7FoWpm5/s/co+H2jicqy9xo1RGh0A775JKy6J26fGHSsegoYOoD/EDTUtWRMHOr1TpQ0yyDi3SeEzJsyku7Vpc4c9H48cvQg1OWMuIKDNeAlpNe7cMl1nfdVUt85yeXWMOKUZfsrCLE+bXLnkf0r3GmxeW21yG/tW7J7aqPFM7QnbrDk3qE4W+QEFO5Mt5Q+TcYRazJAkC+6IS4GGLpUUuicRVYwJnAX5ZR/aCNWRSy8QoMm4wFAydDV+YNYWvzfIrlS65U6N5wkVcIP2RKXQpxhFIbe95eHmSJfpctTZkGG2lMDOgKsxJBYsEKPe0qD2JZmtpAyDAQaOKNivvxIo6ZbZ+hc45lWQrX0MPivn0qqVvLSDxvgJMmK/s501oOIdIecTCJciSSjiY8TkE65uJ4dnljRp1Li4mbGRHLz8j40fLqjPPCUnr1ws0WZQN8+18rJLuR4DaomDA4Lf7PU8iTfI0GMON7Rry5/lhjGs5lpvt9cckJfMfzSXXQeuceoVX9uBqw=

script:
  - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
  - "./mvnw test -B"
  - ".travis/mvn-deploy.sh"
